### PR TITLE
fix sign tx callback with wallet connect

### PR DESCRIPTION
**Pull request by geovgy**
Tested on desktop browser using trust wallet and metamask mobile. Unable to test on mobile browser.

### CODE REVIEW

**Comment by Yuxanju** [comment]
You have to synchronize your wallet and and then you debug it with bech13

**Comment by Yuxanju** [comment]
You have to synchronize your wallet and and then you debug it with bech13

**Comment by Yuxanju** [comment]
You have to synchronize your wallet and and then you debug it with bech13

**Comment by didierkrux** [comment]
https://www.notion.so/bankless/fix-sign-tx-callback-with-wallet-connect-d5237659b97b4e41abb2dc24802531a0

**Review by didierkrux — APPROVED** [review]
Good job @geovgy.
I made a quick code refactor to simplify the logic in case we want to reuse this somewhere else later.
See details in this commit: https://github.com/BanklessDAO/bankless-academy/pull/68/commits/d8dfef2ed2e33d9f8586898d2dfecbd6388b9164

**Pull request merged**
